version: 0.2

phases:
  install:
    commands:
      - echo Building app...
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - aws s3 cp --recursive dist/ s3://$BUCKET_NAME/ --acl=public-read
artifacts:
  files:
    - dist/*
